dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: ulffPfWvuV3VE7f0PqO6+XrcRIeViIyoAxPHRqJpyEgVLrU4HU1L2UW6qk+U8rDF8VugN6Fi5r44w/i++UJKZtn1I2JJi6/AtJgTbay5xReikx94dXzshk3EMUz4Zu9UHVRB6VIe/Fpe8xoTyk3rnVzB06ZKyMZWVlEbNh0JmtfHBeVsaUzpnsPVasbVRJvPg96dhkNF2Vx8oq20kK9ECwTWnb7gR1T4dr7qPwTCXkNjcIq6bHsmX5W8yckhCP2q0um+tHIkHrLHWJxZouEImep8qD6xgT10vgiWIiw2UJC55x1RFvAZOsN1XRgElIz48HX1mSS8wJVyBDgeP0epFsbtudZpenUVfW5NKdSFyzVYtPSmjQuw9XHzTwFrcS5gI4G8ONVDOZ5BymeekCfT8IQGYlBAEesuXeE971LKMASvjotbC8GucR2qMsIpIQLF781je65w8OFR5BlQY4mbRPPUFxYTEqO8P8+cDjvJHid1MH+ePAq7iugd5+ClAqVywwXX+JMPQTV3IEVw7s3FBF3ldkpdGLqJEQ3tKY+a8I7z4N+w8RS/Fv4VrRxd6nXVIUL3XeIxQJunDHoRtfSkmeamQebqEA7tBcAUDBsizMkCwiBzk02MC6WSWubo2eTbmnUA9riHOrkmyDqcLwE8j2RikvVIDZPUucyIqRJQy9I=
